// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBooking.Book.Contexts;

namespace TicketBooking.API.Data.migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20220301194436_AddCustomer")]
    partial class AddCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketBooking.Book.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73155700-71c1-46c6-ae99-aea5525d549d"),
                            Address = "Kolabagan",
                            Age = 26,
                            Name = "Zahid",
                            Salary = 20000
                        },
                        new
                        {
                            Id = new Guid("92ec8722-3419-48bc-b39e-4f46df8ce4d4"),
                            Address = "Khulna",
                            Age = 15,
                            Name = "Jui",
                            Salary = 1500
                        },
                        new
                        {
                            Id = new Guid("38f90328-b1ae-4ce8-b4b2-634e7acb56db"),
                            Address = "BUET",
                            Age = 20,
                            Name = "Rafsan",
                            Salary = 30000
                        },
                        new
                        {
                            Id = new Guid("31f58393-2120-48cb-9196-c29bc21567d7"),
                            Address = "Comila",
                            Age = 40,
                            Name = "Habib",
                            Salary = 50000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
